### ISSUE TITLE
In webGME 1.7.0 FAB throws exceptions

### ISSUE THREAD

**Issue by finger563** [dfst/webgme-fab#8]
e.g. 

``` js
    "exception": {
      "message": "Materialize.toast is not a function",
      "stack": "TypeError: Materialize.toast is not a function
    at http://rcps.isis.vanderbilt.edu/panel/FloatingActionButton/FloatingActionButton.Plugins.js:27:29
    at http://rcps.isis.vanderbilt.edu/dist/webgme.dist.build.js:30:20282
    at Socket.<anonymous> (http://rcps.isis.vanderbilt.edu/dist/webgme.dist.build.js:17:25303)
    at Socket.onack (http://rcps.isis.vanderbilt.edu/socket.io/socket.io.js:5225:9)
    at Socket.onpacket (http://rcps.isis.vanderbilt.edu/socket.io/socket.io.js:5149:12)
    at Manager.<anonymous> (http://rcps.isis.vanderbilt.edu/socket.io/socket.io.js:5522:15)
    at Manager.Emitter.emit (http://rcps.isis.vanderbilt.edu/socket.io/socket.io.js:5657:20)
    at Manager.ondecoded (http://rcps.isis.vanderbilt.edu/socket.io/socket.io.js:4668:8)
    at Decoder.<anonymous> (http://rcps.isis.vanderbilt.edu/socket.io/socket.io.js:5522:15)
    at Decoder.Emitter.emit (http://rcps.isis.vanderbilt.edu/socket.io/socket.io.js:2556:20)"
    },
```

**Comment by finger563** [comment]
From what I can tell it has to do with the `RESULTS`; since it only happens when the plugin finishes and the results are supposed to be shown, but they never show (and this exception is returned).

**Comment by brollb** [comment]
I just tried it this morning and didn't have any problems. From the error, it looks like the problem is with Materialize's toast function being loaded (materialize is used for the styling, etc) on line [19](https://github.com/dfst/webgme-fab/blob/master/src%2Fvisualizers%2Fpanels%2FFloatingActionButton%2FFloatingActionButton.js#L19).

Can you verify that `Materialize.toast` is defined when the FloatingActionButton is defined?

**Comment by brollb** [comment]
I thought we figured this out - is that correct?
